### ISSUE TITLE
Skeleton / Placeholder Guidelines

### ISSUE THREAD

**Issue by jeffdoolittle** [trimble-oss/modus#231] opened 2022-03-22 16:24 UTC
As a user of the design system, I want to have the option to use a skeleton in my application, so that it helps the user with loading times.

- https://getbootstrap.com/docs/5.1/components/placeholders/

**Comment by coliff** [comment] 2023-03-23 14:17
Modus Bootstrap 2 Preview:
https://modus-bootstrap.netlify.app/docs/5.3/components/placeholders/

**Comment by msankaran0712** [comment] 2023-04-21 07:43
Closing as this is a duplicate of https://github.com/trimble-oss/modus/issues/432

**Closed by msankaran0712** 2023-04-21 07:43 UTC
Labels: story, priority:medium, tiger-team
