### ISSUE TITLE
Date picker enhancement to accept any format

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus#486] opened 2023-08-24 06:46 UTC
Submission reviewed by MoAB Aug 15. https://app.clickup.com/t/86858ewpx

More information needed.

**Comment by soniakaukonen** [comment] 2023-09-06 13:53
Overall suggestion is to revisit date picker for better Figma component controls as well as matching web functionality with Figma component functionality.

**Comment by soniakaukonen** [comment] 2023-09-06 14:45
@msankaran0712 to check if this is a bug.

**Comment by msankaran0712** [comment] 2023-09-14 05:16
It is a enhancement and not a bug

**Comment by msankaran0712** [comment] 2023-09-19 14:26
Maha to transfer the issue to web cpomponents

**Comment by msankaran0712** [comment] 2023-09-20 05:42
Closing the issue as nothing to do in Figma and web components has a separate issue https://github.com/trimble-oss/modus-web-components/issues/1709 

cc
@soniakaukonen

**Closed by msankaran0712** 2023-09-20 05:42 UTC
Labels: Figma
